### ISSUE TITLE
DDA-103: Delete tool confirmation dialog + tests

### ISSUE THREAD

**Issue by jvalanen** [DioryMe/diory-browser-electron#103]
## Acceptance criteria & changelog
- Confirm deletion of link or diory
- Delete link or diory (and all links to it) from store and diograph.json
- Confirmation for deleting room (optional)

## Tasks
* [ ] Create dialog component to storybook
* [ ] Trigger modal from delete tool (doesnt have to do anything yet, just show)
* [ ] Implement all the feature tests based on Stories + make those feature tests to pass
* [ ] Unit test DELETE_LINK and DELETE_DIORY actions and reducers
    - Takes as an argument:
        - deleted diory 
        - type of deletion (diory, link or diory with links) 
        - diory in focus (only on link type of deletion)
* [ ] Spec unit logic that is not covered by feature specs

## Design paper

https://paper.dropbox.com/doc/Delete-tool--BGXl~adIGN0NPEcC9R9fdCrRAg-Zsq0CmFTwdvcVb2TQTUam
