### ISSUE TITLE
DDA-39: Deploy pipeline resources with CloudFormation to AWS

### ISSUE THREAD

**Issue by jvalanen** [DioryMe/diory-browser-electron#39]
## Acceptance criteria
- Website can be updated by making changes to `/website` folder and merging new source code to "website" branch
- New binaries can be build and appear on [downloads website](http://dda-downloads.s3-website.eu-north-1.amazonaws.com/) by using build-mac.sh script and uploading the .dmg file to the "dda-downloads" S3 bucket

## TODO
- [x] Public S3 bucket for binaries (index.html will be placed there too)
- [x] latest-mac.html and latest-win.html files to redirect to the binary
- [x] CodePipeline
- [x] Github source action
- [x] CodeBuild for Windows binary
- [x] CodeBuild for UpdateWebsite: copy /website folder contents from repository to dda-downloads bucket: index.html, latest-win.html, latest-mac.html
- [x] IAM roles: task role & execution role & service role
- [x] diograph.com redirects to the downloads page

## Currently out scoped?
- [ ] S3 trigger for pipeline when .dmg file is added: https://docs.aws.amazon.com/codepipeline/latest/userguide/update-change-detection.html#update-change-detection-cfn-s3 (requires Cloudtrail, CloudwatchEvent and CloudwatchEvent trigger for Pipeline and source stage from S3 for the Pipeline)
- [ ] Read Github credentials from SecretsManager (as th !Ref to parameter store didn't work...)
- [ ] Remove the need of setting the version numbers before every build (ability to use multiple sources: .dmg uploaded to S3, Github code and created .exe file => last stage, update website needs all of these...and they need to be passed all the way to there...)
- [ ] Test the whole pipeline thing with new binaries and website (and make video as instructions)
1. Edit website
1. Build .dmg file on mac and upload it to S3 (package-mac.sh script)
2. Verify that the (1) website updates and (2) pipeline triggers and creates .exe file and uploads it to S3 and (3) new .dmg and .exe files are available from diograph.com

**Comment by jvalanen** [comment]
Version 2.0.0 => merged https://github.com/DioryMe/diory-browser-electron/pull/40
